[package]
name = "postgrust"
version = "0.1.0"
authors = ["Christopher <jcp.christopher@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.9"
clap = "2.33.0"
serde_derive = "^1.0.8"
serde = "1.0.8"
postgres = "0.15"
