[pg]

[pg.host1]
host="localhost"
port="5432"
username="latte"
password="cappuccino"
dbname="postgres"

# UNCOMMENT the below section, if you have more than one PostgreSQL physical hosts
#[pg.host2]
#host="localhost"
#port="5432"
#username="latte"
#password="cappuccino"
#dbname="postgres"
